{
    'name': "Billing with Accounting",
    'author': "Nathaniel Lew Aquino",
    'license': 'OPL-1',
    'version': '1.0',
    'summary': "Billing module with invoicing, receipt printing, reports",
    'category': 'Billing',
    'website': 'www.ithinksols.com',
    'depends': ['base', 'account'],
    'data': ['security/ir.model.access.csv',
             'data/ir_sequence_data.xml',
             'data/account_payment_term_data.xml',
             'data/ir_property_data.xml',
             'views/report.xml',
             'views/report_views.xml',
             'views/account_billing_views.xml',
             'views/product_product_views.xml',
             'views/account_invoice_views.xml',
             'views/account_payment_views.xml',
             'wizard/account_billing_generate_views.xml',
             'report/account_invoice_report_views.xml',
             'views/assets.xml',
             'views/account_billing_dashboard_views.xml',
             'wizard/account_billing_generate_disconnect_views.xml',
             ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
